### ISSUE TITLE
Anime fetch result section overlapping with game results

### ISSUE THREAD

**Issue by tchestnut85** [CFsylvester/AniGame#16]
Div containing the anime results overlaps with the game result image. 

![image](https://user-images.githubusercontent.com/67440557/93659508-d69a9900-fa13-11ea-9cf9-c6924ca12fbf.png)

**Comment by CFsylvester** [comment]
I think this will be fixed with the next pull

**Comment by tchestnut85** [comment]
Yup, looks like it is fixed. I'll close it out.
